[libdefaults]
        default_realm = AD.FILLINGHAM.AU
        dns_lookup_realm = false
        dns_lookup_kdc = true
        default_ccache_name = FILE:/run/user/%{uid}/krb5cc

[domain_realm]
        ad.fillingham.au = AD.FILLINGHAM.AU
