[global]
    workgroup = FILLINGHAM
    security = ADS
    realm = AD.FILLINGHAM.AU

    vfs objects = acl_xattr
    map acl inherit = Yes
    store dos attributes = Yes

    # Incoming kerberos tickets will be validated against secrets.tdb only
    # machine account password will not be synced to any keytab file
    kerberos method = secrets only


    # Do not require that login usernames include the default domain
    winbind use default domain = yes
    winbind offline logon = yes
    winbind refresh tickets = yes
    winbind request timeout = 5

    # Default ID mapping configuration for local BUILTIN accounts
    # and groups on a domain member. The default (*) domain:
    # - must not overlap with any domain ID mapping configuration!
    # - must use a read-write-enabled back end, such as tdb.
    idmap config * : backend = tdb
    idmap config * : range = 10000-49999

    # Domain mappings
    idmap config FILLINGHAM : backend = rid
    idmap config FILLINGHAM : range = 65536-99999

    template shell = /bin/bash
    template homedir = /home/%U
