[global]
    workgroup = FILLINGHAM
    security = ADS
    realm = AD.FILLINGHAM.AU

    winbind refresh tickets = Yes
    vfs objects = acl_xattr
    map acl inherit = Yes
    store dos attributes = Yes

    # Allow a single, unified keytab to store obtained Kerberos tickets
    kerberos method = secrets only
    sync machine password to keytab = "/etc/krb5.keytab:sync_account_name:sync_spns:sync_kvno:machine_password"


    # Do not require that login usernames include the default domain
    winbind use default domain = yes
    winbind offline logon = yes
    winbind refresh tickets = yes

    # Default ID mapping configuration for local BUILTIN accounts
    # and groups on a domain member. The default (*) domain:
    # - must not overlap with any domain ID mapping configuration!
    # - must use a read-write-enabled back end, such as tdb.
    idmap config * : backend = tdb
    idmap config * : range = 10000-49999

    # Domain mappings
    idmap config FILLINGHAM : backend = rid
    idmap config FILLINGHAM : range = 65536-99999

    template shell = /bin/bash
    template homedir = /home/%U
