#! /usr/bin/env bash

# When a network interface comes up, tell winbind to try going online
# If the domain controller is reachable, the status will become online, if not, it will stay offline and cached logins will still work

script_name=$(basename "$0")
interface="$1"
action="$2"

function log {
    local message="$1"
    echo "$script_name: $message"
}

log "Script started with interface=$interface and action=$action"

winbind_is_active=$(/bin/systemctl is-active winbind.service)

if [[ "$winbind_is_active" != "active" ]]; then
    log "winbind is not active, exiting"
    exit 0
fi

if [[ "$action" != "up" && "$action" != "vpn-up" ]]; then
    log "action is not up or vpn-up, exiting"
    exit 0
fi

winbind_offline_logon=$(testparm -s --parameter-name "winbind offline logon" 2>/dev/null)

# Convert to lowercase before testing
if [[ "${winbind_offline_logon,,}" != "yes" ]]; then
    log "winbind offline logon is not enabled, exiting"
    exit 0
fi

log "winbind is active and offline logon is enabled, attempting to set status to online"
smbcontrol winbind online
